apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: LoadBalancer
  selector:
    project: {{ .Release.Name }}
  ports:
  - name: {{ .Release.Name }}-port
    protocol: TCP
    port: 80
    targetPort: {{ .Values.container.port }}
